language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

sudo: false

matrix:
  include:
  - php: 7.2
    env:
    - ENVIRONMENT="coverage"

before_script:
  - printf "\n" | pecl install imagick
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - travis_retry composer check-style
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [ "$ENVIRONMENT" == 'coverage' ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi